disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - variable_name
  - xctfail_message

opt_in_rules: # some rules are only opt-in
  - switch_case_on_newline

excluded:
  - Carthage
  - Pods

variable_name:
  min_length: 2  

type_body_length:
  - 400
